config/routes.rb
Rails.application.routes.draw do
  resources :artists, only: %w(index show)
  resources :cds, only: %w(index) do
    get :search, on: :collection
  end
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :cds
end

app/models/cd.rb
class Cd < ActiveRecord::Base
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/cds_controller.rb
class CdsController < ApplicationController
  def index
  end

  def search
    @cds = AmazonSearcher.cds params['search']['keyword'], params['search']['artist'], params['search']['title']
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/index.html.slim
- @artists.each do |artist|
  div
    a href= artist_path(artist)
      = artist.name

app/views/artists/show.html.slim
= @artist.name

app/views/cds/index.html.slim
section.content
  .row
    .col-md-4
      .box.box-info
        .box-header.with-border
          h3.box-title CD検索
          
        = form_tag search_cds_path, method: :get, class: 'form-horizontal'
          .box-body
            .form-group
              = label :artist, 'キーワード', class: 'col-sm-2 control-label'
              = text_field :search, :keyword, class: 'col-sm-10'
            .form-group
              = label :artist, 'アーティスト', class: 'col-sm-2 control-label'
              = text_field :search, :artist, class: 'col-sm-10'
            .form-group
              = label :title, 'タイトル', class: 'col-sm-2 control-label'
              = text_field :search, :title, class: 'col-sm-10'
          .box-footer
            = submit_tag '検索', class: 'btn btn-primary pull-right'
- if @cds.present?
  div
    table.table
      thead.thead-inverse
        tr
          th No
          th イメージ
          th アーティスト
          th タイトル
          th リリース
      - @cds.each.with_index(1) do |cd, i|
        tbody
          tr
            td = i
            td = image_tag cd.jacket_image_url
            td = cd.artist.name
            td = cd.title
            td = cd.release_date.strftime('%F') if cd.release_date

app/views/layouts/application.html.slim
doctype html
html lang='ja'
  head
    title SlimShelf
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    body
      = yield